### PR TITLE
Added Peppermint in the list of tested distributions.

### PR DESCRIPTION
**Pull request by PoorPocketsMcNewHold**
Peppermint, is an Ubuntu-based distribution, tailored to netbooks, with a certain mix of LXDE, Xfce & Cinnamon composing the main desktop environment. Oh, and it has an SSB manager too. 
Since it doesn't change anything from a base Ubuntu that cause a case of packages incompatibility, this pull request can be safely refused.
image

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Sorry for not seeing this sooner. Please see requested change.

**Comment by PoorPocketsMcNewHold** [comment]
I don't see any reviews notes of your part, and hence, know which changes are requested. If you want, you are free to modify my pull requests, in any way.

**Comment by ThatOneCalculator** [comment]
Screenshot_2021-11-05-01-39-57_2560x1440

this has literally been there lol

**Review by ThatOneCalculator — APPROVED** [review]

**Comment by ThatOneCalculator** [comment]
i forgor i can do that lol

**Pull request merged**
