### PR TITLE
use all package managers found on system

### PR DESCRIPTION
**Pull request by Pan00Pernicek**
currently nerdfetch uses only first one that it finds
change i made allows it to count package managers in similiarish way to neofetch
Screenshot_20210310_105449
considering it counts both dnf and rpm it may be good idea to remove one of them (propably dnf as rpm is more universal), what do you think?

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Not only does this look extremely cursed, this kinda sucks for us arch users, I'd say 99% of us don't wanna see pacman alongside yay or paru. 

I would close this, but if you can make a POSIX implementation of this as a `-a` flag, I'll add it. Basically, `nerdfetch` is the default but `nerdfetch -a` would show all package managers.

**Comment by ThatOneCalculator** [comment]
@Pan00Pernicek do you plan on implementing it or should I close this pr?

**Comment by Pan00Pernicek** [comment]
ill try later

**Comment by ThatOneCalculator** [comment]
@Pan00Pernicek u gonna or nah?

**Comment by Pan00Pernicek** [comment]
it seems to work on my machine, but it propably needs more testing

**Comment by ThatOneCalculator** [comment]
```
$ nerdfetch -a  
/sbin/nerdfetch: line 60: qlist: command not found
```
Non posix :pensive: 

Sorry, it was a nice try but I don't think I'll be implementing this.

**Comment by Pan00Pernicek** [comment]
but qlist is in current version already thought

**Comment by ThatOneCalculator** [comment]
No lol

**Comment by Pan00Pernicek** [comment]
https://github.com/ThatOneCalculator/NerdFetch/blob/1372708abaabece2edae63baefea40a471503e13/nerdfetch#L58

**Comment by ThatOneCalculator** [comment]
That's only for Gentoo

**Comment by Pan00Pernicek** [comment]
yea, weird that in my version it somehows finds emerge on your system

**Comment by Pan00Pernicek** [comment]
i think i found cause of it, it seems like when you have `pkg` binary somewhere it tries to run qlist, but it seems like normal nerdfetch have also that issue but it wont most of time, ill try fix it

**Comment by Pan00Pernicek** [comment]
maybe this wont error https://raw.githubusercontent.com/Pan00Pernicek/rfetch/patch-3/nerdfetch

**Pull request closed without merging**
